// <auto-generated />
namespace Abbey_Trading_Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Test_anything001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Test_anything001));
        
        string IMigrationMetadata.Id
        {
            get { return "202310211101050_Test_anything001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
