// <auto-generated />
namespace Abbey_Trading_Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Delete_date_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Delete_date_field));
        
        string IMigrationMetadata.Id
        {
            get { return "202310151443563_Delete_date_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
