// <auto-generated />
namespace Abbey_Trading_Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_expenditure_category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_expenditure_category));
        
        string IMigrationMetadata.Id
        {
            get { return "202310201352313_Add_expenditure_category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
