// <auto-generated />
namespace Abbey_Trading_Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class change_transactions_fields_int : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_transactions_fields_int));
        
        string IMigrationMetadata.Id
        {
            get { return "202405041203197_change_transactions_fields_int"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
