//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abbey_Trading_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessAccount
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Tel_1 { get; set; }
        public string Tel_2 { get; set; }
        public string Tel_3 { get; set; }
        public string Valid { get; set; }
        public string Location { get; set; }
        public Nullable<int> Server_id { get; set; }
    }
}
