//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abbey_Trading_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> added_date { get; set; }
        public string added_by { get; set; }
        public Nullable<int> Server_id { get; set; }
    }
}
