//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abbey_Trading_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealerCust
    {
        public int ID { get; set; }
        public string type { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> added_date { get; set; }
        public string added_by { get; set; }
        public Nullable<int> Server_id { get; set; }
    }
}
