//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abbey_Trading_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenditure_Categories
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Overall_category { get; set; }
        public string Description { get; set; }
        public string Added_by { get; set; }
        public System.DateTime Added_date { get; set; }
    }
}
