//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abbey_Trading_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string product { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public string Rate { get; set; }
        public string Selling_price { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<System.DateTime> Added_date { get; set; }
        public string Added_by { get; set; }
        public Nullable<int> Server_id { get; set; }
        public string Wholesale_price { get; set; }
    }
}
