//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abbey_Trading_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public int id { get; set; }
        public string AppVersion { get; set; }
        public string Messages { get; set; }
        public string MessageAPIKey { get; set; }
        public string MessageUsername { get; set; }
        public string MessageFrom { get; set; }
        public string Active { get; set; }
        public Nullable<System.DateTime> Date_configured { get; set; }
    }
}
