//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abbey_Trading_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Detail
    {
        public int ID { get; set; }
        public string product_name { get; set; }
        public Nullable<int> rate { get; set; }
        public string Qty { get; set; }
        public Nullable<int> total { get; set; }
        public string dea_cust_name { get; set; }
        public Nullable<System.DateTime> added_date { get; set; }
        public string added_by { get; set; }
        public Nullable<int> Invoice_id { get; set; }
        public string Profit { get; set; }
        public string Type { get; set; }
        public Nullable<int> Server_id { get; set; }
    }
}
