//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abbey_Trading_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Tracker
    {
        public int ID { get; set; }
        public Nullable<int> Transaction_id { get; set; }
        public string Paid_amount { get; set; }
        public Nullable<System.DateTime> Added_date { get; set; }
        public string Updated_by { get; set; }
        public Nullable<int> Server_id { get; set; }
    }
}
