//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abbey_Trading_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int ID { get; set; }
        public string type { get; set; }
        public string dea_cust_name { get; set; }
        public Nullable<long> grandTotal { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
        public Nullable<int> discount { get; set; }
        public string added_by { get; set; }
        public Nullable<long> Paid_amount { get; set; }
        public Nullable<int> Return_amount { get; set; }
        public Nullable<long> Total_Profit { get; set; }
        public string Paid { get; set; }
        public string Taken { get; set; }
        public Nullable<int> Server_id { get; set; }
    }
}
