//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abbey_Trading_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string user { get; set; }
        public string Contact { get; set; }
        public string Gender { get; set; }
        public string Added_by { get; set; }
        public string Type { get; set; }
        public Nullable<int> Server_id { get; set; }
    }
}
